language: node_js
sudo: required  # See http://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
node_js:
  - "10"
python:
  - "2.7"
before_install:
  # Override Xenial's default Java version (github.com/travis-ci/travis-ci/issues/10290)
  - export PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
before_script:
  - export PATH="`pwd`/node_modules/.bin:$PATH"
addons:
  chrome: stable
script: gulp presubmit
branches:
  only:
    - master
matrix:
  include:
    - env: BUILD_SHARD="unit_tests"
      addons:
        hosts:
          - pub.localhost
          - sp.localhost
-cache:
  directories:
  - node_modules
  bundler: true
